### ISSUE TITLE
Fails to build with GSL 2.0

### ISSUE THREAD

**Issue by sebastic** [nco/nco#19]
nco 4.5.3 fails to build on Debian unstable with `--enable-gsl`:
```
In file included from ../nco/nco_srm.h:17:0,
                 from ../nco/libnco.h:56,
                 from ncap2_utl.hh:52,
                 from ncoGrammer.g:29,
                 from fmc_gsl_cls.hh:39,
                 from fmc_gsl_cls.cc:10:
../../config.h:423:31: error: floating constant in preprocessor expression
 #define NCO_GSL_MINOR_VERSION 2.0
                               ^
fmc_gsl_cls.cc:120:6: note: in expansion of macro 'NCO_GSL_MINOR_VERSION'
 # if NCO_GSL_MINOR_VERSION >= 8
      ^
...
```
This seems to be caused by the recently started [gsl transition](https://release.debian.org/transitions/html/auto-gsl.html) from 1.16 to 2.0.

The issue is caused by this code in `configure.ac` that doesn't handle GSL >= 2.0:
```shell
 652 # Assumes GSL version in form 1.[0-9]+  extract minor version only
 653         GSL_VER="`${GSL_CONFIG} --version`"
 654         GSL_VER=`echo "${GSL_VER}" | sed -e 's/^1\.//'`
 655         if test "x${GSL_VER}" = 'x'; then
 656             # 20100115: Fix for machines like bluefire that lack gsl-config
 657             GSL_VER='4'
 658         fi
 659         AC_DEFINE(ENABLE_GSL,1,Compile operators with GSL support)
 660         AC_DEFINE_UNQUOTED(NCO_GSL_MINOR_VERSION,${GSL_VER},GSL minor version number)
 661         AC_MSG_NOTICE([GSL support enabled])
```
I'm not sure how GSL 2.0 should be handled in NCO, I guess `NCO_GSL_MAJOR_VERSION` should be added now and all `# if NCO_GSL_MINOR_VERSION >= <n>` checks changed to take the `NCO_GSL_MAJOR_VERSION` into account too.

**Comment by czender** [comment]
thanks bas! we'll sort this out in the next few days...

On 11/6/15 02:54, Bas Couwenberg wrote:
> nco 4.5.3 fails to build on Debian unstable with |--enable-gsl|:
>
> |In file included from ../nco/nco_srm.h:17:0, from ../nco/libnco.h:56,
> from ncap2_utl.hh:52, from ncoGrammer.g:29, from fmc_gsl_cls.hh:39, from
> fmc_gsl_cls.cc:10: ../../config.h:423:31: error: floating constant in
> preprocessor expression #define NCO_GSL_MINOR_VERSION 2.0 ^
> fmc_gsl_cls.cc:120:6: note: in expansion of macro
> 'NCO_GSL_MINOR_VERSION' # if NCO_GSL_MINOR_VERSION >= 8 ^ ... |
>
> This seems to be caused by the recently started gsl transition
> <https://release.debian.org/transitions/html/auto-gsl.html> from 1.16 to
> 2.0.
>
> The issue is caused by this code in |configure.ac| that doesn't handle
> GSL >= 2.0:
>
>   652# Assumes GSL version in form 1.[0-9]+ extract minor version only
>   653         GSL_VER="`${GSL_CONFIG} --version`"
>   654         GSL_VER=`echo "${GSL_VER}" | sed -e 's/^1\.//'`
>   655if  test  "x${GSL_VER}"  ='x';  then
>   656# 20100115: Fix for machines like bluefire that lack gsl-config
>   657             GSL_VER='4'
>   658fi
>   659         AC_DEFINE(ENABLE_GSL,1,Compile operators with GSL support)
>   660         AC_DEFINE_UNQUOTED(NCO_GSL_MINOR_VERSION,${GSL_VER},GSL minor version number)
>   661         AC_MSG_NOTICE([GSL support enabled])
>
> I'm not sure how GSL 2.0 should be handled in NCO, I guess
> |NCO_GSL_MAJOR_VERSION| should be added now and all |# if
> NCO_GSL_MINOR_VERSION >= <n>| checks changed to take the
> |NCO_GSL_MAJOR_VERSION| into account too.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nco/nco/issues/19>.
>

-- 
Charlie Zender, Earth System Sci. & Computer Sci.
University of California, Irvine 949-891-2429 )'(

**Comment by czender** [comment]
Henry committed a patch that divides GSL_VER into major and minor versions and appears to work on both GSL 1.x and 2.x libraries. Patch tested on 1.X machines. Hope someone can test this on 2.X GSL.

**Comment by czender** [comment]
Fortunately MacPorts just updated to GSL 2.0. Tested this patch there, works fine. Closing this issue.
