### ISSUE TITLE
undefined reference to `nc_set_log_level`: NCO fails to build with NetCDF 4.7.1 on Ubuntu 18.04

### ISSUE THREAD

**Issue by neumannd** [nco/nco#155]
This issue might be related to [Issue building 4.7.8 with netcdf-C 4.6.2: multiple definition of nc_open_mem](https://sourceforge.net/p/nco/discussion/9831/thread/e6faa0b8c1/).

Therefore, I am not sure whether this is a NetCDF-issue or a NCO-issue.

# System

* Ubuntu 18.04
* gcc 7.4.0
* Linux Kernel 5.0.0-31
* NetCDF 4.7.1 (freshly compiled; all tests passed successfully)
* NCO 4.7.2, 4.7.6, and 4.8.1

# Error Description

I configure NCO without any issues. The compilation process (just `make`, no `make -j2` or similar) breaks due to missing `nc_set_log_level`.

# Error Output

NCO 4.8.1 returns

```
ncatted.c:(.text+0x6e8): undefined reference to `nc_set_log_level'
./.libs/libnco.so: undefined reference to `nc_open_memio'
./.libs/libnco.so: undefined reference to `nc_close_memio'
./.libs/libnco.so: undefined reference to `nc_create_mem'
```

NCO 4.7.2 and 4.7.6 just return

```
ncbo.c:(.text+0xdbd): undefined reference to `nc_set_log_level'
```

or

```
ncap.c:(.text+0xd86): undefined reference to `nc_set_log_level'
```

# No error with NetCDF 4.6.0 and 4.6.1

If I compile with NetCDF 4.6.0 (from Ubuntu 18.04 Package repository) or NetCDF 4.6.1 (from my conda/python installation), everything works fine.

**Comment by czender** [comment]
NCO 4.8.1 has no problem finding nc_set_log_level() and the rest when pointing to netCDF 4.6.2, 4.7.0, 4.7.1 on my systems. You may need to build netCDF with the --enable-logging option, though I do not think so. It seems more likely to me that your NCO compilation is finding a different netCDF than 4.7.1.

**Comment by neumannd** [comment]
Ok. Thanks for the quick reply. A "-L..." pointing to the default system library folder (containing an old NetCDF version) was prepended to my LDFLAGs, which I did not realize. Now it worked out. Sorry for the false alarm.
