### ISSUE TITLE
Build failure with NCO 5.0.1 using icc

### ISSUE THREAD

**Issue by mathomp4** [nco/nco#244]
I'm looking at updating my [base libraries](https://github.com/GEOS-ESM/ESMA-Baselibs) and decided to try out NCO 5.0.1. I do a test build on two machines. One is macOS and the other is Linux. The macOS build using clang/clang++/ifort (2021.2) and the Linux build is Intel 19.1.3 (icc/icpc/ifort). On the mac, everything builds happily, on Linux, I get:
```
nco_rgr.c(4850): error: "msk_out" must be specified in a variable list at enclosing OpenMP parallel pragma
  # pragma omp parallel for default(none) firstprivate(dmn_cnt_in,dmn_cnt_out,dmn_srt,dmn_id_in,dmn_id_out,tally,var_val_dbl_in,var_val_dbl_out,wgt_vld_out) private(dmn_idx,dmn_nbr_in,dmn_nb
r_out,dmn_nbr_max,dst_idx,has_mss_val,idx,idx_in,idx_out,idx_tbl,in_id,lnk_idx,lvl_idx,lvl_nbr,mss_val_dbl,rcd,thr_idx,trv,val_in_fst,val_out_fst,var_id_in,var_id_out,var_nm,var_sz_in,var_sz
_out,var_typ_out,var_typ_rgr,var_val_crr) shared(col_src_adr,dmn_nbr_hrz_crd,flg_add_fll,flg_frc_nrm,flg_msk_apl,flg_msk_out,flg_rnr,fnc_nm,frc_out,lnk_nbr,out_id,row_dst_adr,sgs_frc_nm,sgs_
frc_in,sgs_frc_out,sgs_msk_nm,wgt_raw,wgt_vld_thr)
```
So, it must be icc related. It is in an `__INTEL_COMPILER` block, so maybe ICC is a bit wonky.

I can try with icc 2021.2 if you think it would help diagnosis.

**Comment by mathomp4** [comment]
Note: I'm also trying to read the code to figure out if `msk_out` should be `shared`, `private` or `firstprivate`. I mean, I know I can add it to any of them, but I'm using this as a good test of my (nigh-nonexistent) C coding skills. :smile:

**Comment by czender** [comment]
Thanks for reporting this. Double-checking the compilation with `icc` is not yet done automatically, and has tripped me up before. Your patch is correct and will be in the next NCO release.

**Comment by mathomp4** [comment]
@czender Thanks! I might look at creating a patch for now...but then patching in GNU Make is annoying so I might just be lazy and wait for 5.0.2 😄
